development:
 adapter: postgresql
 encoding: utf8
 database: sensors_development
 pool: 5
 username: dev
 password: dev

test:
 adapter: postgresql
 encoding: utf8
 database: sensors_test
 pool: 5
 username: dev
 password: dev

production:
 adapter: postgresql
 encoding: utf8
 database: sensors_production
 pool: 5
 username: dev
 password: dev